### ISSUE TITLE
Error when adding VentilationFan with VentilationControl object

### ISSUE THREAD

**Issue by marctavenier** [ladybug-tools/honeybee-energy#1012]
When adding a VentilationFan with a VentilationControl object that includes an On-Off schedule, OpenStudio throws an error. The error message is as follows:

> SWIG director method error. NoMethodError: undefined method `setOpeningAreaFractionSchedule' for #<OpenStudio::Model::ZoneVentilationDesignFlowRate:0x0000021c9585b1b0>
> 
> Traceback (most recent call last):
> C:/Program Files/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/to_openstudio/ventcool/fan.rb:108:in `to_openstudio'
> C:/Program Files/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/to_openstudio/geometry/room.rb:442:in `block in to_openstudio'
> C:/Program Files/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/to_openstudio/geometry/room.rb:440:in `each'
> C:/Program Files/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/to_openstudio/geometry/room.rb:440:in `to_openstudio'
> C:/Program Files/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/to_openstudio/model.rb:473:in `block in create_rooms'
> C:/Program Files/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/to_openstudio/model.rb:471:in `each'
> C:/Program Files/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/to_openstudio/model.rb:471:in `create_rooms'
> C:/Program Files/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/to_openstudio/model.rb:189:in `create_openstudio_objects'
> C:/Program Files/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/to_openstudio/model.rb:93:in `to_openstudio_model'
> C:/Program Files/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/measures/from_honeybee_model/measure.rb:116:in `run'

If I understand correctly the assigned schedule affects the OpeningAreaFraction, but a VentilationFan does not have an OpeningAreaFraction.

**Comment by chriswmackey** [comment]
Thanks for finding and reporting this bug, @marctavenier . I am able to recreate it and I will push a fix shortly.

**Comment by chriswmackey** [comment]
I have the fix ready and I verified that it's working correctly:

![image](https://github.com/ladybug-tools/honeybee-energy/assets/5567574/09168412-9826-410e-aba4-55f4e208f633)
