### ISSUE TITLE
Add Window Material .properties Extension Classes

### ISSUE THREAD

**Issue by ed-p-may** [ladybug-tools/honeybee-energy#1038]
Hi @chriswmackey 

I wonder if you would be open to adding a few more `.properties` to [properties.extension.py](https://github.com/ladybug-tools/honeybee-energy/blob/master/honeybee_energy/properties/extension.py) so that we can extend a few more classes? Specifically, we would like to add a `.properties` class for:

- [EnergyWindowMaterialGlazing](https://github.com/ladybug-tools/honeybee-energy/blob/8a896d6b4d687118782f3be4a06132a0251c82b0/honeybee_energy/material/glazing.py#L34)
- [EnergyWindowMaterialSimpleGlazSys](https://github.com/ladybug-tools/honeybee-energy/blob/8a896d6b4d687118782f3be4a06132a0251c82b0/honeybee_energy/material/glazing.py#L525C7-L525C40) 
- [EnergyWindowMaterialGas](https://github.com/ladybug-tools/honeybee-energy/blob/8a896d6b4d687118782f3be4a06132a0251c82b0/honeybee_energy/material/gas.py#L312)
- [EnergyWindowMaterialGasMixture](https://github.com/ladybug-tools/honeybee-energy/blob/8a896d6b4d687118782f3be4a06132a0251c82b0/honeybee_energy/material/gas.py#L464)
- [EnergyWindowMaterialGasCustom](https://github.com/ladybug-tools/honeybee-energy/blob/8a896d6b4d687118782f3be4a06132a0251c82b0/honeybee_energy/material/gas.py#L665C7-L665C36)
- [EnergyWindowFrame](https://github.com/ladybug-tools/honeybee-energy/blob/8a896d6b4d687118782f3be4a06132a0251c82b0/honeybee_energy/material/frame.py#L17C7-L17C24)

- - - 
The reason for adding these properties is so that we can extend them as part of the Honeybee-REVIVE (Phius) extension we are working on.

- - -
If you don't object to the above, I can put together a PR and send over? Similar to [PR#861](https://github.com/ladybug-tools/honeybee-energy/pull/861) that we submitted previously. 

@ed-p-may / @PH-Tools

**Comment by chriswmackey** [comment]
Thanks, @ed-p-may . I don't have any objections and I think it's a good idea. Feel free to put together a PR and I'll review/merge.

**Comment by ed-p-may** [comment]
Ok great, I just sent though [PR#1039](https://github.com/ladybug-tools/honeybee-energy/pull/1039). Let me know if you think you'd like any changes though. Thanks!

**Comment by mostaphaRoudsari** [comment]
@ed-p-may, should we close this issue now that the PR is merged?

**Comment by ed-p-may** [comment]
Yes: this is resolved now. Thanks!
