### ISSUE TITLE
Make It Easy for People to Create New EnergyPlus Bldg Programs with the New API

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-energy#11]
Note to future Chris:  when we make the new API for Honeybee Energy, it should be made in a way that is easy for people to make new building programs if they have a list of schedules and loads.  This really seems to be an area where object-oriented programming will help significantly (ie. we have building program objects instead of just a building program attribute of HBZones).

**Comment by chriswmackey** [comment]
I just wanted to note that making classes for building programs will be next on my list after finishing the implementation of schedules.

**Comment by AntoineDao** [comment]
Reckon we can break this down into bite sized issues for people to pick up during hacktoberfest? No worries if not.

**Comment by chriswmackey** [comment]
Actually, I think we can close this issue now that we have the [ProgramType](https://github.com/ladybug-tools/honeybee-energy/blob/master/honeybee_energy/programtype.py#L20) object here in the `honeybee_energy` library.  Essentially, all of the infrastructure is in place on this repo to enable the creation of programs and we just have to link it with the OpenStudio standards Space Types and expose it on some components.
