### ISSUE TITLE
Find a Clean Way of Generating OpenStudio Objects from HBObjects

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-energy#12]
There is a major API design issue with implementing toOsObjects(). OpenStudio objects can only be created under a Model object which means that, to get an OpenStudio string for a surface, one needs to initiate the OpenStudio model first, then add a zone to a the model, then add the surface to the zone and then get the whole model together.

There are three ways I can think of dealing with the issue but I want to get everyone's thoughts here before the issue is tackled:

1) We create toOsObjects() functions for each honeybee object but these functions require an input OpenStudio model to initiate and return a model with the zone added.  In this case, the functions that add surfaces to zones and glazing to surfaces will be called when the HBZone.toOsObj(model) function is called.  These functions can be called by anyone building an OpenStudio model who has the model object ready to go. The benefit of this is that we can make use of OpenStudio API, which will make the code much more concise, particularly for HVAC.  The downside of this is that it makes it necessary to build a whole OpenStudio model to get the OpenStudio string.  It may also make it unclear about how we should backwards translate OpenStudio models to HBZones.  Examples of this implementation include:
```
import OpenStudio
from honeybee.room import Room

room = Room(origin=(0, 0, 3.2), width=4.2, depth=6, height=3.2, rotationAngle=45)
room.addFenestrationSurface(wallName='back', width=2, height=2, sillHeight=0.7)

model = OpenStudio.model()
model = room.toOsObj(model)
```

2) Honeybee Objects include no functions to translate them to an OpenStudio model.  All of the methods to create OpenStudio models are in their own OSModel class, which requires inputs for HBZones, Run Period, etc.  This same class could also include translators from osm files to Honeybee objects.  Again, we get the benefit of using the OpenStudio API and we have clarity about how to translate back/forth between HB and OpenStudio.  We have worsened the reliance on requiring an OS model to get the OSString, though.  Examples of this include:
```
from honeybee.room import Room
from honeybee.osmodel import OSModel
from ladybug.epw import EPW

room = Room(origin=(0, 0, 3.2), width=4.2, depth=6, height=3.2, rotationAngle=45)
room.addFenestrationSurface(wallName='back', width=2, height=2, sillHeight=0.7)

epw = EPW("C:\ladybug\myclimate.epw")

model = OSModel(room, epw)
model.setRunPeriod([1,1,1], [12,31,24])
```

3) Because OpenStudio models are essentially text files using ASCII, we can have functions that are toOsStr() instead of toOsObj().  While this allows us to get an OS string without having to generate a whole model, we are still going to have to pass unique ID's into these functions for the zones and glazing surfaces because these are referenced within the OS Strings.  My biggest worry here is that I can't possibly imagine adding HVAC systems without the help of OpenStudio API.  I can see people getting desperate with the time it takes to add in new HVAC capabilities such that workarounds develop where people translate the HBObjects to strings and convert these to models just to be able to add HVAC systems.  Examples of code to do this include:
```
from honeybee.room import Room

room = Room(origin=(0, 0, 3.2), width=4.2, depth=6, height=3.2, rotationAngle=45)
room.addFenestrationSurface(wallName='back', width=2, height=2, sillHeight=0.7)

osmModelFile= open("C:\ladybug\myModel.osm, 'wb')
modelUid = "ABCDE"
osmModelFile.write(room.toOsStr(modelUid ))
```

Let me know any preferences or thoughts.
-Chris

**Comment by chriswmackey** [comment]
I just wanted to make a note of our current plan for addressing this situation, which is to write out a JSON of the honeybee model and then use an OpenStudio measure to parse the JSON into an osm. This is definitely not the most elegant or efficient solution to this problem but it is the one that can be most readily implemented in a cross-platform manner. It therefore allows us to make progress on working towards our goals without getting paralyzed by trying to solve all of these comparability problems at once.  Maybe after we have an initial implementation of the measure, we might try translating it to work with specific OpenStudio bindings and maybe we can even try to get it to work with our own custom bindings. But the first step is just to agree on a schema and use the Ruby measures.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey, I think we can jut close this issue for now since as you mentioned the problem has been addressed differently and this issue is more of a distraction at this point.

**Comment by chriswmackey** [comment]
I missed your comment here a few months ago, @mostaphaRoudsari . Ok, let's close it.
