### ISSUE TITLE
Add CLI commands to add resources to the standards library

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-energy#149]
The one thing that I can do with these commands that you can't do by just writing the non-abridged JSON into the standards folder is make sure the sub-objects are added into their respective folder. If you just write a non-abridged construction JSON into the user library right now, the materials of that construction won't show up in the materials library (essentially they only exist for that construction and they don't exist as a resource to be used elsewhere in the standards library). So a CLI command to add a construction to a library will actually add it as an abridged construction to the library and add the materials into the materials folder of the standards library. As the command does this, it can also check to be sure that we don't write duplicate materials into the library. The duplication is ok when we have non-abridged objects since, as I said, a material for a non-abridged construction only exists for that construction. But, if we are writing the materials of a construction into the materials folder of the standards library, there's a real danger of having duplicate materials where one material overwrites the other. So the command will check to be sure we don't do this.

**Comment by MingboPeng** [comment]
If the new object created by user through C#, I will add a GUID to its identifier to ensure it's never the same as others. 

But there is a case when creating a object with sub-objects from standards library or previously added from other projects, this should not be counted as the duplicated identifier, it is a shared object.

I am also fine with either way, let's just throw an error for now if that is easier for you.

**Comment by chriswmackey** [comment]
I just wanted to add an update here for how we imagine the behavior of the command working:

> I think we would probably make it illegal to overwrite the constructions that ship with the plugin (in honeybee_energy_standards). However, it should be straightforward to overwrite existing user-defined constructions. The command can have an --overwrite option that allows you to replace the old user-defined object. 

This should be pretty straightforward to implement.

**Comment by chriswmackey** [comment]
We can finally close this out with all of the nice commands that we added here:

https://github.com/ladybug-tools/honeybee-energy/pull/956
https://github.com/ladybug-tools/honeybee-energy/pull/958
