### ISSUE TITLE
Add Internal Mass to honeybee-energy Rooms

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-energy#207]
I know that this feature isn't used as much as some of the other energy simulation features but we should add it for the sake of saying that all legacy features are supported.  I'm sure that it's also useful in making hVAC sizing calculations more realistic.

To do this, we will need to use:
* [InternalMassDefinition](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-3.0.0-doc/model/html/classopenstudio_1_1model_1_1_internal_mass_definition.html)
* [InternalMass](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-3.0.0-doc/model/html/classopenstudio_1_1model_1_1_internal_mass.html)

**Comment by MaxMarschall** [comment]
Hi @chriswmackey, we have a specific project where we will be needing this feature within the next few weeks and it would be great if we could do it in LBT V1 since we also want to use the airflowNetwork. If you are able to bump this one up in the list it would be very much appreciated!

**Comment by chriswmackey** [comment]
This is definitely one of the easier ones to implement as there's not too much to figure out. I'll see if I can get to is soon.

**Comment by brearleyjonathon** [comment]
I am in a similar position to @MaxMarschall ! would be amazing to have in LBT V1! thank you for all your work @chriswmackey
