### ISSUE TITLE
Shade with holes cannot be translated to OSM

### ISSUE THREAD

**Issue by MingboPeng** [ladybug-tools/honeybee-energy#238]
![image](https://user-images.githubusercontent.com/9031066/85489992-ecc4c480-b59e-11ea-9bf6-a4589ff80f72.png)

**Comment by chriswmackey** [comment]
We already established that this is not a bug in honeybee-energy.  The exported OSM and IDF are all correct and include the holes.  It's a bug in the Openstudio viewer, which is based on @theo-armour 's viewer.

So I am closing this issue.
