### ISSUE TITLE
Translate AirWalls to the AFN

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-energy#344]
I'm just going to paste @saeranv 's thoughts here for now:

I think there's two ways we could do it. First we could just model a crack with a large flow coefficient and a flow exponent set to 0.5. That would model a hole-shaped crack with turbulent air flow. 
We could also derive the flow coefficient based on the orifice air flow equation for different shape holes:

![image (1)](https://user-images.githubusercontent.com/5567574/91686079-55459a00-eb2a-11ea-9491-7696664fed59.png)

Multiplied by a discharge coefficient, density, and area of hole. 
This would be a simple method of modeling air flow. But it would only solve for a single speed of air flow moving in one direction.
A second method is to add an always-open door or window. The air flow through an opening is modeled using the same orifice air flow equation above, but applied at different heights across the opening. So you get differential air flow like this:

![image](https://user-images.githubusercontent.com/5567574/91686086-5b3b7b00-eb2a-11ea-912d-0b9cdfcaa4d4.png)

So, for example, if you had buoyancy  two zones with different temperatures, you would want to model the resulting two-way buoyancy-driven flows caused by different air pressures at different heights in the zone.

I would expect the 2nd method to take a lot longer to simulate though, although maybe we should test that assumption.

I'm leaning towards the 2nd one now that I understand it better.

**Comment by saeranv** [comment]
@chriswmackey 

Sorry for the late review. Everything looks good in your changes. I have a minor comment, which is to reference the flow coefficient derivation back to the ELA formula. It's a more straightforward derivation then using the orifice integration I originally derived the formula from, and so will be more useful as a reference.

Here's my suggested change. 

> derive (large) flow coefficient for interzone air flow from the formula for mass flow rate from effective leakage # area, with a 0.65 discharge.[1]
> 
> Note:
> [1] LLC, Big Ladder Software. “AirflowNetwork:MultiZone:Surface:EffectiveLeakageArea.” Accessed September 3, 2020. https://bigladdersoftware.com/epx/docs/9-3/input-output-reference/group-airflow- network.html#airflownetworkmultizonesurfaceeffectiveleakagearea.

**Comment by saeranv** [comment]
@chriswmackey 

Nevermind, just learned the EP team might add a SimpleOpening to the Air wall (once we add a bug report to their repo)[1], in which case we'll be changing this method anyway. They've said this crack derivation method is okay, but it's obviously better to capture the two-way flow. 

[1] https://unmethours.com/question/47107/best-way-to-model-interzone-airflow-through-air-walls-with-afn/

**Comment by chriswmackey** [comment]
I just wanted to post an update here that the air walls are currently translated now but the translation isn't as good as it can be in E+ 9.4. So I am going to leave this issue open until we have upgraded to the new E+ and made sure that Air Boundaries are translated as SimpleOpenings and HorizontalOpenings.

**Comment by chriswmackey** [comment]
No that we officially upgraded to E+ 9.4, I think we can close this one out!
