### ISSUE TITLE
Add "other side coefficient" boundary conditions to boundarycondition.py model

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-energy#407]
This should be implemented just like the adiabatic boundary condition by adding it to the [boundarycondition.py module](https://docs.google.com/document/d/1FS_343EzyrIRZCe5U0y-dzKzcUf6-1Xn3-L7Karmu3M/edit?usp=sharing) and then extending the honeybee-core boundarycondition module in [_extend_honeybee.py](https://github.com/ladybug-tools/honeybee-energy/blob/master/honeybee_energy/_extend_honeybee.py). 

On the Grasshopper side of things, we can expose this with a component that creates the boundary condition object, which can be plugged into the `_bc_` input of the relevant components.

**Comment by rafael-a** [comment]
Hi @chriswmackey ,

I'm trying to extend the boundary construction library to include the GroundSlab and GroundBasement items and, if I understand correctly, it's implemented in a similar way as this. If you could give me some basic directions, I think it could be helpful to have this set of options in the library of additional boundary conditions.

So far, I am testing one of the BC to find my way around it (_GroundSlabPreprocessorAverage_). Although I infer I have broken any possible code rule here, I'll share what I'm trying so far.

1. Add another class to boundarycondition.py, replicating the adiabatic one.
![image](https://user-images.githubusercontent.com/25599446/103641951-c969d180-4f52-11eb-92a0-97852c85101d.png)


2. Add another set of boundary condition to _extend_honeybee.py
![image](https://user-images.githubusercontent.com/25599446/103642057-ec948100-4f52-11eb-9b4c-2e75b43b9e96.png)


3. Test in gh, where it throws the error _1. Solution exception:global name 'GroundSlabPreprocessorAverage' is not defined_ both in the case where I define the new BC and if try a regular one.
![image](https://user-images.githubusercontent.com/25599446/103642262-31201c80-4f53-11eb-9e27-3f47216bfd54.png)

I have to say that I have little knowledge of what I'm doing, and I have mostly copy pasted the adiabatic objects and replaced certain text strings. 😅 

Thanks, and happy new year!
Rafael

**Comment by chriswmackey** [comment]
We can probably also make [surfacepropertyconvectioncoefficients](https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-advanced-surface-concepts.html#surfacepropertyconvectioncoefficients) available in the same commit.
