### ISSUE TITLE
Add  honeybee validate Object

### ISSUE THREAD

**Issue by michaldengusiak** [ladybug-tools/honeybee-energy#486]
Would be possible to add validator for these objects:

- ProgramType
- ProgramTypeAbridged
- ScheduleFixInterval
- ScheduleFixIntervalAbridged
- ScheduleRuleSet
- ScheduleRuleSetAbridged
- ScheduleTypeLimit

**Comment by chriswmackey** [comment]
Will get to it as soon as I can.
