### ISSUE TITLE
Add Radiant HVAC Templates

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-energy#526]
I think this should be done fairly similarly to the way it is implemented in Legacy where an Internal Source material can be put in a material layer of a construction. The only difference will be that people can use this special material type to customize the pipe spacing and thickness.

Then, if the Room has a Radiant HVAC assigned to it, this internal source layer will get connected to low-temperature hot/cold water loops following a template specified by the user. Given what already exists in the OpenStudio Standards gem, I think we can easily support the following Radiant templates:

* DOAS_Radiat_Chiller_Boiler
* DOAS_Radiant_Chiller_ASHP
* DOAS_Radiant_Chiller_DHW
* DOAS_Radiant_ACChiller_Boiler
* DOAS_Radiant_ACChiller_ASHP
* DOAS_Radiant_ACChiller_DHW
* DOAS_Radiant_DCW_Boiler
* DOAS_Radiant_DCW_ASHP
* DOAS_Radiant_DCW_DHW
* Radiat_Chiller_Boiler
* Radiant_Chiller_ASHP
* Radiant_Chiller_DHW
* Radiant_ACChiller_Boiler
* Radiant_ACChiller_ASHP
* Radiant_ACChiller_DHW
* Radiant_DCW_Boiler
* Radiant_DCW_ASHP
* Radiant_DCW_DHW

To implement these templates, we'll just start with what is offered for FCU systems and lower the loop temperatures before connecting up to the internal source.

**Comment by TfedUD** [comment]
@chriswmackey 
This is something topical to the project done in design builder that I abhor design builder for: while knowing how to IronBug it:
   with what I've learned from the round of ```user_data``` in HBE:   Be happy to "next on my list" this unless there is more pressing that some minion attention to would be preferred?

**Comment by TfedUD** [comment]
Big excite!!! 🥳🍾
