### ISSUE TITLE
Construction Decompose Values

### ISSUE THREAD

**Issue by BenGottkehaskamp** [ladybug-tools/honeybee-energy#557]
Hey,

Can somebody help me with this issue. I used the honeybee construction components to create my own test material. The problem is if I decompose the Construction i do not get any Values back. Otherwise when i use the constructions form the Radiance libary it does give me values back, thus the component is not broken. 

I was wondering even tho i do not get values back, is the simulation working correctly?

What is happening here?

![Screenshot 2021-01-25 115628](https://user-images.githubusercontent.com/77965926/105697073-62fa2280-5f04-11eb-94cb-41bed5f8db5e.png)

**Comment by BenGottkehaskamp** [comment]
We did made some simulations with different selfmade materials and it does affect the outputs of the thermal comfort, thus the materials are working, only the decomposeComponent is not working correctly from my perspective since it is giving out <null> outputs.

**Comment by mostaphaRoudsari** [comment]
Hi @BenGottkehaskamp, you should post this question on the forum. Also this is related to the legacy Grasshopper plugin.

https://discourse.ladybug.tools
