### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/honeybee-energy#7]

**Comment by adityakaria** [comment]
Hey there! I'm new to this repository, and am willing to contribute to this issue on updating the README. Could you guide me on where I can get started?

**Comment by asha15** [comment]
@AntoineDao  Hi. I would like to work on this issue.can i get some more information?

**Comment by AntoineDao** [comment]
This is one for @mostapharoudsari I reckon as he raised the issue :smile:

**Comment by mostaphaRoudsari** [comment]
We can start with something similar to what we have for honeybee but I believe you need to know the project pretty well to update the Readme file. @chriswmackey thoughts?

**Comment by chriswmackey** [comment]
Sorry for the late reply here. I do not recommend anyone tackle this issue unless they are really familiar with the project and how we are organizing the new python libraries. Right now, we don't need anything like the honeybee repo but something more like the [honeybee-core repo](https://github.com/ladybug-tools/honeybee-core)

**Comment by chriswmackey** [comment]
This has been addressed via https://github.com/ladybug-tools/honeybee-energy/pull/43
