### ISSUE TITLE
Allow the use of honeybee JSONs in the library of constructions + schedules

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-energy#72]
Right now, we allow users to add custom materials, constructions, and schedules to their user library by dropping IDFs into these folders](). But I can see that, if we want these user libraries to be a shared resource that different plugins/interfaces can write to / read from, we should allow people to drop in honeybee JSONs as well.

This will also bring the construction and schedule folders in line with how the constructionset and programtype folders work since these folders always expect honeybee JSONs.

I don't think it will be that much extra code to enable this.  We just need to add in `if` statement that checks the file extension .idf or .json) and then either uses the current `extract_all_from_idf` method or uses the `from_dict` method.

**Comment by MingboPeng** [comment]
@chriswmackey  To add to this. We should also be accepting the new energyplus Idf-Json format as well.

**Comment by chriswmackey** [comment]
That is the plan in the long run, @MingboPeng . Because the epJSON format uses a custom `.epJSON` file extension, we can use some logic like this to figure out how to parse in the user libraries:
```
if file.lower().endswith('.idf'):
    # parse it in as an IDF
elif file.lower().endswith('.epjson'):
    # parse it in as an epJSON
elif file.lower().endswith('.json'):
    # parse it in as a honeybee JSON
```
I think I am going to hold off on implementing full support for `.epJSON` files right now but, at some point, we will add `to_epjson` and `from_epjson` to most of the Python classes, which will support the processes like that above.

**Comment by chriswmackey** [comment]
This has been addressed via https://github.com/ladybug-tools/honeybee-energy/pull/85
