### ISSUE TITLE
Issues with if Schdedule: ...

### ISSUE THREAD

**Issue by PH-Tools** [ladybug-tools/honeybee-energy#838]
Hi all, 

I wonder about a small issue I keep running into when working with [ScheduleRuleset](https://github.com/ladybug-tools/honeybee-energy/blob/a16c453116344dc016a3dd02dbb028548ece1daa/honeybee_energy/schedule/ruleset.py#L24) objects. Because (I think) [`__len__`](https://github.com/ladybug-tools/honeybee-energy/blob/a16c453116344dc016a3dd02dbb028548ece1daa/honeybee_energy/schedule/ruleset.py#L1583) is implemented on this object, when testing if it exists - ie:

```python
if hb_room.properties.energy.people.schedule:
    # Go do some stuff...
```

if the `_schedule_rules` field is empty, this will resolve to `False`, even though the schedule *does* exist. 
![image](https://user-images.githubusercontent.com/69652712/136087987-40a0c580-62c4-4b73-afe8-baaa9a9ed3a4.png)

I find the only way to test for *does the schedule exist* is:
```python
if hb_room.properties.energy.people.schedule is not None:
    # Now I can go do some stuff....
```

So that's ok, but it was mighty confusing until I sorted out what was happening there? So I wonder:
- Is there a way to implement this so that if the user does `if schedule:` on an existing schedule, it will resolve to True? Which I believe would be the more expected result.
- Is there some use-case where its important to resolve to False if the user does `if schedule:` on a valid schedule, but with an empty `_schedule_rules` ? 
- What does it 'mean' when a `_schedule_rules` is empty? Is that an important state? Is there a better default state?

This comes up most often since the `hb_room.properties.energy.__.schedule` fields are very often `None`, and so when working with these objects I do a lot of checking for existence before proceeding.

best
-Ed (@PH-Tools)

**Comment by chriswmackey** [comment]
Thanks for pointing this out @PH-Tools . I agree it's weird and unintentional that it evaluates to False. It's a quick fix and I'll push it now.
