### ISSUE TITLE
Heat Capacity in FaceEnergyAttr is kg/K-m² not kJ/K-m²

### ISSUE THREAD

**Issue by guiyuki** [ladybug-tools/honeybee-energy#893]
Hi, i'm using HB in grasshopper and spotted the "kg" instead "kJ" in the text.
Can you guys change it please?

**Comment by mostaphaRoudsari** [comment]
Hi @guiyuki, thank you for reporting this. Can you share a screenshot to make it easier to understand the issue. Thanks!

**Comment by guiyuki** [comment]
Hi
Heat capacity should be in Joules (J) instead of grams (g)?
![image](https://user-images.githubusercontent.com/36683059/185616114-74b59390-a7be-432b-bee4-25bb70a99bee.png)

**Comment by chriswmackey** [comment]
Thanks, @guiyuki . You are right and I just fixed this in the SDK docs here:

https://github.com/ladybug-tools/honeybee-energy/pull/895

I'll fix it in the Grasshopper plugin shortly.

**Comment by chriswmackey** [comment]
I just fixed the grasshopper plugin:

https://github.com/ladybug-tools/honeybee-grasshopper-energy/pull/339
