### ISSUE TITLE
Add Properties to HB-Energy Materials

### ISSUE THREAD

**Issue by PH-Tools** [ladybug-tools/honeybee-energy#903]
Hi @chriswmackey 

Before submitting a PR, I wanted to see if would be ok with me adding Properties to the Honeybee-Energy [EnergyMaterial](https://github.com/ladybug-tools/honeybee-energy/blob/master/honeybee_energy/material/opaque.py) classes, similar to how we've done for the other HBE types? I can add it using a similar pattern to [PR-823](https://github.com/ladybug-tools/honeybee-energy/pull/823), if you think that would be an acceptable addition?

The one last item real feature that I would like to add for the Honeybee-PH plugin is to add a Heterogeneous Material option (for modeling in, like, an insulated cavity with studs every 16", etc....) so thinking that I would add all of that extra info to the Material's .properties.ph, But first, I'd need to add the basic properties extension to the EnergyMaterials.

If you think that's ok, I can send along the PR with that addition for your review?

thanks,
@PH-Tools

**Comment by chriswmackey** [comment]
Hey @PH-Tools ,
This sounds good to me and I'm actually surprised that we didn't add this with the earlier PR. I guess we just didn't have a need for it until now but please feel free to work on it and send a PR whenever you have it ready.

Also, I recommend following an implementation that's similar to what you did with constructions, where you add the properties to the base class that all of the materials are inheriting from. This should minimize the amount of new code that you need to add.

**Comment by PH-Tools** [comment]
Great, [PR submitted](https://github.com/ladybug-tools/honeybee-energy/pull/904) with those changes. thanks!
