### ISSUE TITLE
Removing '_Space' fails in case a room has multiple spaces

### ISSUE THREAD

**Issue by snjsomnath** [ladybug-tools/honeybee-energy#977]
https://github.com/ladybug-tools/honeybee-energy/blob/f76222320811116c01a773b9fda05e26c02da277/honeybee_energy/run.py#L940C32-L940C32

Removing '_Space' fails in case a room has multiple `Spaces`

```
room_id = 'Flr1_NONE_Floor1_Room1_Space_1'
room_id[:-6]
>>Flr1_NONE_Floor1_Room1_S
```

My zones in the OSW gbxml:
```
<Space id="Flr1_NONE_Floor1_Room1_Space_10" zoneIdRef="Flr1_NONE_Floor1_Room1_10" buildingStoreyIdRef="Flr1_NONE_Floor1">
        <Name>Flr1_NONE_Floor1_Room1</Name>
        <Area>44.465736</Area>
        <Volume>133.397209</Volume>
      </Space>
```

**Comment by chriswmackey** [comment]
Hi @snjsomnath ,

I'm going to need some more context here. Generally speaking, Honeybee Rooms map to Spaces in OpenStudio (and by extension gbXML). It's more that the concept of Zone has not been implemented (yet) in Honeybee schema. But, if/when we do implement it, Zone will be something that exists above the Room, not below it (much like how the Room.story property is implemented now). More info on our thinking can be found here:

https://discourse.pollination.cloud/t/model-geometry-discussion-balancing-model-details-and-rooms-for-load-calculations-versus-energy-modeling/2474/2

So I don't understand how a "Room has multiple Spaces". Can you elaborate on what you are trying to achieve here?

**Comment by snjsomnath** [comment]
Hi @chriswmackey ,

Apologies for this. I did misunderstand how this is supposed to work. Hence, I am closing this issue with this comment.

For context, I am trying to generate a detailed energy model from a geojson that we automatically generate from GIS data.
I was incorrectly generating the HBModel which resulted in having more than one zone per room. I have since corrected that issue and now only have one zone per room.

You can see more of this here [DTCC Workflow](https://github.com/dtcc-platform/dtcc/blob/dev/sanjayworkflow/workflows/workflow_geojson_to_DF.py)
Thank you for looking into this!
/Sanjay
